### ISSUE TITLE
should i train 7000 epochs ?

### ISSUE THREAD

**Issue by zoldaten** [muxamilian/wyhiwys#2]
i started train process and it calculates about 7000 epochs to train.
should i wait so long or about 100 epochs will be enough ?

**Comment by muxamilian** [comment]
I guess you have a very small dataset? I use a simple formula to compute the number of epochs: https://github.com/muxamilian/wysiwyh/blob/161e593173eef5d7eb4bbd7cac3e94302680e5fc/learn.py#L81
Maybe get a larger dataset?

**Comment by zoldaten** [comment]
i found out that 100 epochs more than enough. 
now i fight with:
`underflow of audio queue `
while playing audio.

**Comment by muxamilian** [comment]
Maybe neural net inference is so slow that it can’t do it real time?

**Comment by muxamilian** [comment]
Closing this, let me know if something doesn’t work!
